---
title: Connor Murphy
description: I’m Connor, a digital designer based in Denver.
url: connormurphy.design
permalink: pretty
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
collections:
  projects:
    output: true
    sort_by: date
    permalink: "/:collection/:path/"
    future: false
