title: 'Connor Murphy'
url: 'connormurphydesign.com'
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
collections:
  projects:
    output: true
    sort_by: date
    permalink: /:collection/:path/
    future: false