title: 'Connor Murphy'
role: 'Designer'
email: 'connormurphydesign@gmail.com'
url: 'connormurphydesign.com'
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
collections:
  projects:
    output: true