---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: _config.yml
  label: Site Settings
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
- type: document
  path: _data/content.yml
  label: Content
- type: heading
  label: Pages
- type: document
  path: index.html
  label: Homepage
- type: document
  path: contact.html
  label: Contact
upload_dir: assets/img
public_path: "/assets/img"
front_matter_path: "/assets/img"
use_front_matter_path: false
file_template: ":year:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
