backend:
  name: git-gateway
  branch: master
media_folder: '/assets/img/'
public_folder: '/assets/img/'
logo_url: /assets/img/boandco.svg
collections:
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Categories', name: 'listing_type', widget: 'string', comment: 'Example: Art Direction, Website Design, etc.' }
      - { label: 'Type', name: 'type', widget: 'string', comment: 'Example: Landing page'}
      - { label: 'Body', name: 'body', widget: 'markdown' }