---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: text
  name: listing_type
  label: listing_type
- type: text
  name: type
  label: type
- type: text
  name: timeline
  label: timeline
- type: field_group_list
  name: contributers
  label: contributers
  fields:
  - type: text
    name: role
    label: role
  - type: text
    name: name
    label: name
  - type: text
    name: url
    label: url
- type: field_group_list
  name: contributions
  label: contributions
  fields:
  - type: text
    name: label
    label: label
- type: datetime
  name: date
  label: date
- type: file
  name: thumbnail
  label: thumbnail
