---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  hidden: false
  default: project
  config:
    required: true
- type: text
  name: title
  label: Name
- type: text
  name: listing_type
  label: Categories
  description: 'Example: Art Direction, Website Design, etc.'
- type: text
  name: type
  label: Type
  description: 'Example: Landing page'
- type: text
  name: description
  label: Short Description
- type: text
  name: timeline
  label: timeline
- type: field_group_list
  name: contributers
  label: Contributers
  fields:
  - type: text
    name: role
    label: Contributor Role
  - type: text
    name: name
    label: Contributor Name
  - type: text
    name: url
    label: Contributor Website
    description: "<em>Optional</em>"
  description: People who participated in the project.
- type: field_group_list
  name: contributions
  label: My Contributions
  fields:
  - type: text
    name: label
    label: Label
- type: datetime
  name: date
  label: Date
  description: Projects are ordered by date (oldest first), and the date is never
    visible.
- type: file
  name: thumbnail
  label: Thumbnail Image
pages:
- _projects/invision-events.md
- _projects/shopify.md
- _projects/whenwewander.md
