---
label: Project
hide_body: false
fields:
- type: text
  name: layout
  default: default
  label: Template
  hidden: true
- type: text
  name: title
  label: Project name
- type: text
  name: type
  label: Labels
- type: datetime
  name: date
  label: Date
  description: Projects are sorted by date
- type: file
  name: thumbnail
  label: Thumbnail
pages:
- _projects/invision-events.md
